# to perform grid search for any parameters, write them as a list. e.g. to try batch sizes of 2,3,4, write batch_size: [2,3,4]
# to use 2 controls for controlnet, separate the names of the preprocesses and their scales with '-'. e.g. preprocess_name: 'depth_zoe-lineart_realistic' control
# controlnet_conditioning_scale: '0.75-0.25'

video_name: "dog_wind_30f"  # specify the name of the video existing in the data/mp4_videos folder (e.g. data/mp4_videos/truck.mp4)
preprocess_name: 'softedge_pidinet'  # specify the name of the condition used for the video (e.g. depth_zoe condition)
control_image_path_1: '' #'/home/cgvsl/P76111131/ControlNet_AnimalPose/__assets__/output/fox_turn_head_27/pose' #'/home/cgvsl/P76111131/PersonalizedVideo/__assets__/pose/istockphoto_dog_run'
control_image_path_2: '' #'/home/cgvsl/P76111131/PersonalizedVideo/__assets__/pose/istockphoto_dog_run'

enable_mask: true
mask_blur_factor: 1 # -1 for no blur
mask_image_path: '/home/cgvsl/P76111131/RAVE/data/mask/dog_wind_all'

batch_size: 4  # denotes the batch size of grids (e.g. 4 grids run in parallel)
batch_size_vae: 1  # denotes the batch size for the VAE (e.g. 1 grid runs in parallel for the VAE)

cond_step_start: 0.0  # denotes the step to start conditioning

controlnet_conditioning_scale: 0.8  # denotes the scale of the conditioning
controlnet_guidance_end: 1.0  # denotes the end of the controlnet guidance
controlnet_guidance_start: 0.0  # denotes the start of the controlnet guidance

give_control_inversion: true  # denotes whether to give control to the inversion

grid_size: 3  # denotes the size of each grid (e.g. grid_size x grid_size)
sample_size: -1  # denotes the number of grids to be generated (-1 for the full video)
pad: 1  # denotes the padding of the video (if 1, use the same video)
guidance_scale: 7.5  # denotes the scale of the guidance
inversion_prompt: ''  # denotes the inversion prompt

is_ddim_inversion: true  # denotes whether to use ddim for inversion
is_shuffle: true  # denotes whether to applying shuffling between the grids

negative_prompts: ""  # denotes the negative prompts
num_inference_steps: 100  # denotes the number of inference steps during the sampling process
num_inversion_step: 100  # denotes the number of inversion steps during the inversion process

positive_prompts: "A golden retriever puppy sticking its head out of a car window moving through a landscape filled with tall trees"
save_folder: 'dogwindow/goldenretrieverpuppy/without_border'  # denotes the name of the folder to save the results under results

seed: 0  # denotes the seed
model_id: 'None'  # None to use stable diffusion v1.5, otherwise use the model id
# model_id: ['./CIVIT_AI/diffusers_models/130072/realisticVisionV60B1_v51VAE']  # None to use stable diffusion v1.5, otherwise use the path of the civitai model
# lora_path: 'None'
lora_path: '/home/cgvsl/P76111131/MasaCtrl/lora/golden_puppy/training1_60_0.0003/glodenpuppy'
lora_scale: 1.0
lora_name: 'goldenretrieverpuppy'

border_size: -1
border_type: 'black'